# Generated by Django 5.1.2 on 2024-10-11 20:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            10,
                            11,
                            20,
                            33,
                            14,
                            396770,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            10,
                            11,
                            20,
                            33,
                            14,
                            396770,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="participants", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=500)),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            10,
                            11,
                            20,
                            33,
                            14,
                            397849,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.thread"
                    ),
                ),
            ],
        ),
    ]
